### ISSUE TITLE
Feedback needed! What's your experience using tomo?

### ISSUE THREAD

**Issue by mattbrictson** [mattbrictson/tomo#120]
Hi! 👋 Thanks for checking out tomo!

I'd love to hear how you are using tomo, what works well, and what could be improved. Please leave a comment here or feel free to reach out to me at opensource@mattbrictson.com.

**Comment by ymolina** [comment]
Hello there!

Have just started using tomo in the last week for deploying an existing app to a new hosting environment managed by a third party (have been a grateful user of your capistrano-mb library for a good number of years before that).

So far, so great. I really like the simplicity of it's DSL, and generally just how clear everything is.

There is just one little hack that I've had to make, in the rake helper of the rails plugin, to ensure that the rake command is used instead of rails, in order to be able to use it with my rails 4.2 app.
(https://github.com/mattbrictson/tomo/blob/35fc3027cc7563b9bd1bc2348903f440c8e73989/lib/tomo/plugin/rails/helpers.rb#L10).

Also, very minor, I've noticed that the env.setup task does not like environment variables to be defined as integers, you need to either prompt for the value, or just add them as strings in set env_vars. 

I will let you know if I come across anything else, or I feel that something is lacking.

Thanks for the great work!

**Comment by mattbrictson** [comment]
Thanks for the feedback! Great to hear you've had a positive experience. I didn't consider Rails 4.2 so the fact that it works for older Rails for the most part is a pleasant surprise.

The `rake` vs `rails` issue is a legitimate bug, a copy-paste mistake way back in 5c086492cecb600c4b62291cbbd8aa5a6dd76dae. The name of the helper is `rake` and the documentation says it should run `bundle exec rake`, not `bundle exec rails`. I'll get that fixed.

> the env.setup task does not like environment variables to be defined as integers

Interesting... there is probably just a `.to_s` missing somewhere. I'll look into it.

> capistrano-mb

Wow, that's a throwback! 😲

**Comment by BilalBudhani** [comment]
Just deployed a small Rails 6 side project on a VPS and the experience so far has been great. I had to do very minimal config related changes to setup & deploy my application. I like how lightweight `tomo` is compared to `capistrano`, also, DSL is so simple and intuitive. 

I'm going to migrate some more side projects to `tomo` and share my feedback. Thank you for putting all the efforts in this gem.

**Comment by qx** [comment]
I'm from capistrano-mb, thanks for your code.  Does tomo support rails6 's deploy?

**Comment by mattbrictson** [comment]
@qx Yes, tomo supports Rails 6 out of the box. Here is a tutorial that walks through deploying a sample Rails 6 app: https://tomo-deploy.com/tutorials/deploying-rails-from-scratch/

**Comment by qx** [comment]
ruby 2.7.1 install always fail on ubuntu18.04, suggested to. use "ruby-install --install-dir ~/.rbenv/versions/2.7.0 ruby 2.7.1" to replace default rbenv install command .

**Comment by mattbrictson** [comment]
> ruby 2.7.1 install always fail on ubuntu18.04, suggested to. use "ruby-install --install-dir ~/.rbenv/versions/2.7.1 ruby 2.7.1"

This combination should work. I just followed the [official tomo tutorial](https://tomo-deploy.com/tutorials/deploying-rails-from-scratch/) with Ubuntu 18.04.3 (LTS) x64 and Ruby 2.7.1 worked out of the box, no workarounds needed.

<details>

```
• rbenv:install
export PATH=$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH && curl -fsSL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash
Installing rbenv with git...
Initialized empty Git repository in /home/deployer/.rbenv/.git/
Updating origin
From https://github.com/rbenv/rbenv
 * [new branch]      master     -> origin/master
 * [new tag]         v0.1.0     -> v0.1.0
 * [new tag]         v0.1.1     -> v0.1.1
 * [new tag]         v0.1.2     -> v0.1.2
 * [new tag]         v0.2.0     -> v0.2.0
 * [new tag]         v0.2.1     -> v0.2.1
 * [new tag]         v0.3.0     -> v0.3.0
 * [new tag]         v0.4.0     -> v0.4.0
 * [new tag]         v1.0.0     -> v1.0.0
 * [new tag]         v1.1.0     -> v1.1.0
 * [new tag]         v1.1.1     -> v1.1.1
 * [new tag]         v1.1.2     -> v1.1.2
Branch 'master' set up to track remote branch 'master' from 'origin'.
Already on 'master'
make: Entering directory '/home/deployer/.rbenv/src'
gcc -fPIC     -c -o realpath.o realpath.c
gcc -shared -Wl,-soname,../libexec/rbenv-realpath.dylib  -o ../libexec/rbenv-realpath.dylib realpath.o 
make: Leaving directory '/home/deployer/.rbenv/src'

Installing ruby-build with git...
Cloning into '/home/deployer/.rbenv/plugins/ruby-build'...

Running doctor script to verify installation...
Checking for `rbenv' in PATH: /home/deployer/.rbenv/bin/rbenv
Checking for rbenv shims in PATH: OK
Checking `rbenv install' support: /home/deployer/.rbenv/plugins/ruby-build/bin/rbenv-install (ruby-build 20200520-10-g157c719)
Counting installed Ruby versions: none
  There aren't any Ruby versions installed under `/home/deployer/.rbenv/versions'.
  You can install Ruby versions like so: rbenv install 2.2.4
Checking RubyGems settings: OK
Auditing installed plugins: OK

All done!
Note that this installer doesn't yet configure your shell startup files:
1. You'll want to ensure that `~/.rbenv/bin' is added to PATH.
2. Run `rbenv init' to see instructions how to configure rbenv for your shell.
3. Launch a new terminal window to verify that the configuration is correct.

cat .bashrc
Writing 4041 bytes to .bashrc
rbenv versions
Installing ruby 2.7.1 -- this may take several minutes
CFLAGS=-O3 rbenv install 2.7.1
Downloading ruby-2.7.1.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.7/ruby-2.7.1.tar.bz2
Installing ruby-2.7.1...
Installed ruby-2.7.1 to /home/deployer/.rbenv/versions/2.7.1

rbenv global 2.7.1
```

</details>

 You mention `ruby-install` which is not a standard part of rbenv. Perhaps your machine has some sort of custom Ruby setup? If this happens on a clean Ubuntu setup please open an issue with more details.

> puma can not change port after deploy

Specify e.g. `set puma_port: 3030` in your `.tomo/config.rb` and then rerun `tomo setup` and `tomo deploy`. Refer to the [documentation for tomo puma settings](https://tomo-deploy.com/plugins/puma/).

**Comment by qx** [comment]
> > ruby 2.7.1 install always fail on ubuntu18.04, suggested to. use "ruby-install --install-dir ~/.rbenv/versions/2.7.1 ruby 2.7.1"
> 
> This combination should work. I just followed the [official tomo tutorial](https://tomo-deploy.com/tutorials/deploying-rails-from-scratch/) with Ubuntu 18.04.3 (LTS) x64 and Ruby 2.7.1 worked out of the box, no workarounds needed.
> 
> You mention `ruby-install` which is not a standard part of rbenv. Perhaps your machine has some sort of custom Ruby setup? If this happens on a clean Ubuntu setup please open an issue with more details.
> 
> > puma can not change port after deploy
> 
> Specify e.g. `set puma_port: 3030` in your `.tomo/config.rb` and then rerun `tomo setup` and `tomo deploy`. Refer to the [documentation for tomo puma settings](https://tomo-deploy.com/plugins/puma/).
thanks for your reply.  I don't know why ,I install three machine ,2 of  mac osx,and 1 cloud machine, all build faild with ruby 2.7.1,may be miss some essensial lib.
>> ruby 2.7.1 install always fail on ubuntu18.04, suggested to. use "ruby-install --install-dir ~/.rbenv/versions/2.7.1 ruby 2.7.1"

**Comment by alliedarmour** [comment]
I just tried with a small application and I love it. When I started deploying apps with capistrano, I had to fix so many issues at first. Tomo just worked. Clean, simple DSL, no surprises. Keep the great work up!

**Comment by qx** [comment]
wonderfull tool! thanks for sharing

**Comment by uxxman** [comment]
Just tried it out for a complex app with multiple app servers (puma) and separate background workers (sidekiq) and everything works really great. Really clear and concise DSL and less boilerplate as compared to capistrano ❤️ 

Why the name 'tomo'? Just curious 🙈 

Another question, in default tomo config template, **setup** and **deploy** tasks have some duplicate runs for 
* git:create_release
* core:symlink_shared
* bundler:install

any reason for keeping them in setup tasks too? Shouldn't they just belong to **deploy** task only?

and once again great work 👍

**Comment by mattbrictson** [comment]
@uxxman thanks for the feedback! Great to hear that tomo is working for you. ❤️ 

> Why the name 'tomo'?

Mostly I was looking for a short 3 or 4 letter gem name that wasn't taken. Since Ruby has a history of using Japanese gem names a found the word "tomo" apparently means "friend" in Japanese and I wanted to build a friendly tool so I went with that. 🙂 

> setup and deploy tasks have some duplicate runs for git:create_release, core:symlink_shared, bundler:install

That's because part of what `setup` does is prepare the database using `rake db:create`, etc. To be able to run that task, tomo needs a copy of the app, and it needs to bundle install the dependencies. And running bundler requires that the symlink to `shared/bundle` exists. So it all basically works out that those tasks are needed. Note that `setup` runs inside a different releases directory, which defaults to `/tmp/tomo`. So you can think of `tomo setup` as creating a throwaway release in a temporary location just for the purposes of running setup commands like `rake db:create`.

**Comment by uxxman** [comment]
> Mostly I was looking for a short 3 or 4 letter gem name that wasn't taken. Since Ruby has a history of using Japanese gem names a found the word "tomo" apparently means "friend" in Japanese and I wanted to build a friendly tool so I went with that. 🙂
Interesting 😃 Your tomo is making many new tomos 😄 🚀 

> That's because part of what `setup` does is prepare the database using `rake db:create`, etc. To be able to run that task, tomo needs a copy of the app, and it needs to bundle install the dependencies. And running bundler requires that the symlink to `shared/bundle` exists. So it all basically works out that those tasks are needed. Note that `setup` runs inside a different releases directory, which defaults to `/tmp/tomo`. So you can think of `tomo setup` as creating a throwaway release in a temporary location just for the purposes of running setup commands like `rake db:create`

Understood 👍 Was just curious since, in a multi server setup, the database is already created and the newly spawned servers just connected with it, so I removed db:create and was wondering if it is ok to remove the duplicate tasks as well. But if they are only needed to make **rake db:create** work, then I think it's ok to remove them in my case.

**Comment by molfar** [comment]
I think you should get rid for all OS specific setups, like ruby, node, bundler. And focus only on deploying stage: checkout, migrate, compile, release, reload app. Just tried you tool with latest ubuntu 20.10 - and no one ssh commands work with preinstalled rbenv (command not found).

**Comment by uxxman** [comment]
> I think you should get rid for all OS specific setups, like ruby, node, bundler. And focus only on deploying stage: checkout, migrate, compile, release, reload app.

Since the **setup** and **deploy** tasks consist of other smaller tasks, you can cherry pick the ones you need and remove the ones that are not needed for your usecase. So, you can remove the tasks that setup ruby, node, bundler from your setup task and handle them separately on your own.

**Comment by mazharoddin** [comment]
Hi,
Initially, I was a bit skeptical to use tomo because I got used to with capistrano-mb and was feeling lost due to some errors related to my VM setup(not related to tomo, but appeared as because of tomo).

But, after using it for more than a couple of weeks, I would say it's a lot easier than capistrano-mb for deployment. However, capistrano-mb handles provisioning and setup a little better.  
Mainly installing postgresql etc for the first-time deployment. 

But, overall tomo is great..thanks @mattbrictson for this awesome gem.

**Comment by mattbrictson** [comment]
Thanks everyone for the feedback! Keep it coming 🙂 

> capistrano-mb handles provisioning and setup a little better. Mainly installing postgresql etc for the first-time deployment.

Agreed, tomo is less ambitious in terms of provisioning. This was intentional on my part because I have less time to support open source projects these days, so I want tomo's scope to be fairly narrow. I focused more on giving tomo a robust plugin system, so that provisioning tools could be added later, perhaps as separate gems built by other contributors.

Ideally tomo could do everything, including setting up PostgreSQL, NGINX, and an HTTPS certificate from certbot. Maybe it will get there someday! If I had to choose one of those, I think that PostgreSQL would probably be next. No promises yet. 🙂 

> I think you should get rid for all OS specific setups, like ruby, node, bundler.

Ah, one person says tomo should do more, and another person says tomo should do less. I guess I can't please everyone! My perspective is that a tool that does no provisioning and focuses only on deployment already exists: it's called capistrano. 🙂 My goal is to distinguish tomo from capistrano by being more "batteries included".

**Comment by mazharoddin** [comment]
Hi @mattbrictson, 

I understand and I am glad that you could able to spend time on open source projects and provide your valuable time on support etc. I appreciate it. 

Yeah, the modular approach is cool, plugins can be added or removed based on the requirement. 

True, it's difficult to please everyone, and trying to please everyone is like not pleasing anyone :) 

But, I would like tomo to be like an end-to-end gem for rails deployments. 
So provisioning and handling post-deployment setup differentiate it from Capistrano. 

Thanks.

**Comment by musashimm** [comment]
Hi! I just migrated from Mina in one of my projects in no more than 20 minutes. Documentation is very good. And custom tasks plugins are very good, too. Awesome project. Thank You.

**Comment by mattbrictson** [comment]
Closing in favor of GitHub Discussions. If you have any ideas or feedback to share, please use the [Discussions](https://github.com/mattbrictson/tomo/discussions) tab. Thanks!
