### ISSUE TITLE
where is production.log

### ISSUE THREAD

**Issue by qx** [mattbrictson/tomo#176]
I'm not sure what'wrong ,even I have set 
```
Rails.logger = Logger.new(STDOUT)
Rails.logger.level = Logger::DEBUG
Rails.logger.datetime_format = "%Y-%m-%d %H:%M:%S"
Rails.application.configure do
  config.logger = ActiveSupport::Logger.new("log/#{Rails.env}.log")
end
```
In enviroment.rb, and I can see `development.log` in development mode correctly.
I can see log only in /var/log/syslog, production.log always empty.  settings are all default

**Comment by mattbrictson** [comment]
The default tomo config sets the env var `RAILS_LOG_TO_STDOUT=1`. This means that Rails will not create a `production.log` file. Instead the output will go through puma to wherever systemd is configured to store puma's stdout. You can access that output using the `journalctl` command that is part of systemd.

Tomo provides a convince for accessing `journalctl`:

```
$ tomo run puma:log
```

See more documentation here: https://tomo-deploy.com/plugins/puma/#pumalog

If you prefer the traditional `production.log`, then all you should need to do is unset the `RAILS_LOG_TO_STDOUT` env var and then restart puma, like this:

```
$ tomo run env:unset RAILS_LOG_TO_STDOUT
$ tomo run puma:restart
```

You'll also want to remove `RAILS_LOG_TO_STDOUT: "1"` from the `env_vars` setting in your tomo config.

If you are using a standard Rails and tomo config then the log file should be at `%{shared_path}/log/production.log`.

I just verified this using a Rails app I deploy with tomo and it works. Here is the relevant section of my Rails `config/environments/production.rb` (I believe this is the default configuration generated by `rails new`):

```ruby
  # Use the lowest log level to ensure availability of diagnostic information
  # when problems arise.
  config.log_level = :debug

  # Prepend all log lines with the following tags.
  config.log_tags = [:request_id]

  # Use default logging formatter so that PID and timestamp are not suppressed.
  config.log_formatter = ::Logger::Formatter.new

  # Use a different logger for distributed setups.
  # require 'syslog/logger'
  # config.logger = ActiveSupport::TaggedLogging.new(Syslog::Logger.new 'app-name')

  if ENV["RAILS_LOG_TO_STDOUT"].present?
    logger           = ActiveSupport::Logger.new($stdout)
    logger.formatter = config.log_formatter
    config.logger    = ActiveSupport::TaggedLogging.new(logger)
  end
```

---


Looking at your config, this seems problematic:

```ruby
Rails.logger = Logger.new(STDOUT)
```

That tells Rails to send all logging output to stdout and to ignore the log file configuration. I recommend sticking to the default configuration Rails gives you when you generate an app using `rails new`.

**Comment by mattbrictson** [comment]
> I have set... in `enviroment.rb`

You shouldn't ever have to modify this file in a Rails app. By default Rails will create `<environment>.log` log files unless you set the `RAILS_LOG_TO_STDOUT` env var as I explained in my previous comment.

**Comment by mattbrictson** [comment]
@qx did you get this working? Can I close this issue?
