### ISSUE TITLE
Why not switch to unix sockets comunication by default?

### ISSUE THREAD

**Issue by vizcay** [mattbrictson/tomo#194]
Hi, I was studing tomo systemd service and socket default configuration files for puma. Looks interesting and simpler than Capistrano :ok_hand:.

Any reason why using TCP sockets by default? If using a reverse proxy on the same VPS a unix socket is faster (https://stackoverflow.com/questions/14973942/tcp-loopback-connection-vs-unix-domain-socket-performance).

**Comment by mattbrictson** [comment]
Hi @vizcay, thanks for the great question. I considered this and the short answer is that I decided to go with TCP for to make it as easy as possible to get an app up and running.

Using TCP, someone can verify their app is working by visiting `http://host:3000/` from their browser. Conceptually this is very straightforward and easy to confirm. I want tomo users to get to that "it works!" moment with as little friction as possible.

If tomo were to use unix sockets by default, that would significantly raise the level of complexity needed to get to "hello world". You would need something like Nginx, for example, to serve as the reverse proxy. Installing and configuring Nginx is a whole separate problem that I do not want tomo to have to deal with just to get an app running. Perhaps an expert deployment would get to that point eventually, but I want to keep the barrier to entry low.

Finally I think deployment tooling these days is trending toward horizontal scaling via load-balanced TCP. I have worked on apps deployed via kubernetes, heroku, AWS, etc. and they all tend to follow a pattern of app nodes run `rails server` (i.e. TCP) and then an infrastructure layer (kubernetes services, heroku routing, ALB, etc.) distributes HTTP traffic across those nodes. So standardizing tomo on TCP by default fits into that familiar pattern for me.

All that said, tomo doesn't prevent you from changing to unix sockets if you want to eke out some extra performance. You'd have to create your own systemd config templates and then configure tomo to use them, like this:

```ruby
# .tomo/config.rb
set puma_systemd_service_template_path: "./templates/puma-service.erb"
set puma_systemd_socket_template_path: "./templates/puma-socket.erb"
```

But personally, overall I think the simplicity of TCP wins for me in the end. I know from experience that getting a deployment working with an Nginx reverse-proxy can be tricky. It is nice to be able to hit port 3000 of the Rails server and say "at least I know the app itself is working". Using a unix socket always made things harder to troubleshoot for me.

**Comment by vizcay** [comment]
Hi @mattbrictson, thanks for your thorough answer. My point was that I belive most users starting with tomo mostly will be deploying only one VPS at first, way before needing horizontal scaling via load balancing. It is possible to use curl to test a unix socket endpoint too: `curl --unix-socket tmp/sockets/puma.sock http://myapp.com`, but of course you need nginx or another reverse proxy to use it in production.

I hope to be able to switch some of our apps to tomo from capistrano 3 and have more feedback, tomo looks great.
