### ISSUE TITLE
How to use postgresql?

### ISSUE THREAD

**Issue by mazharoddin** [mattbrictson/tomo#210]
Hi Matt,
I am trying to deploy rails 6 app using tomo, but I am unable to find out how to specify postgresql db setup. 
I tried to pass postgresql db name, but the setup is failing. Pls, let me know how I can use postgresql using Tomo.

**Comment by mattbrictson** [comment]
Hi @mazharoddin , great question.

Assuming you have a PostgreSQL database already created, then  you just need to specify the `DATABASE_URL` env var so that Rails knows how to connect to it.

When you first run `tomo setup`, it will prompt you to provide a value for `DATABASE_URL`. You can also change the value at any time using this command:

```
$ tomo env:set DATABASE_URL
```

For PostgreSQL, the `DATABASE_URL` should look like this:

```
postgres://PG_USER:PG_PASSWORD@PG_HOST:PG_PORT/PG_DATABASE_NAME
```

Replace the `PG_*` placeholders with the actual values for your database.

For example, at AWS, a PostgreSQL URL might look like this:

```
postgres://jlmxxkwfzsbf:REDACTED@ec2-29-31-95-205.compute.amazonaws.com:5432/9idvnkiv3rf7
```

**Comment by mazharoddin** [comment]
Ok, thanks. 
I will try and let you know if it's working. 
Thanks.

**Comment by mazharoddin** [comment]
Hi @mattbrictson,
It's working fine now, thanks a lot.

However, I still find Capistrano-mb was easy to configure and was hassle-free. 
With tomo, the setup was failing while installing node and ruby. I had to try several times for proper installation.

Another issue I faced was ruby version mismatch because tomo was picking up the incorrect ruby version from .ruby-version file.

For some reason, my .ruby-version has ruby version as "ruby-2.7.0", but it should be just "2.7.0".
Due to this issue ruby installation was failing. It was successful once I updated .ruby-version file.  
  
However, deployment was easy once the setup was completed. Still, I am facing errors related to asset precompilation. But, it's due to my project setup.

Thanks.

**Comment by mattbrictson** [comment]
Thanks for your feedback! The auto-detection of the `.ruby-version` is a relatively new feature and it seems you found an edge case that it doesn't support. I'll log a bug report.

You also mentioned that tomo had trouble installing node. How did you solve that problem?

**Comment by mazharoddin** [comment]
Hi @mattbrictson,
Sure.
Looks like the issue is not related to tomo, but the virtual appliance itself. I was getting checksum errors for any long-running installations which download files from repositories. 

The issue is related to windows Hyper-V setting. The checksum issue got resolved after disabling Hyper-v, so now tomo is working fine.

Thanks.

**Comment by mazharoddin** [comment]
Thanks a lot for your support. Have a great day!!
