### ISSUE TITLE
Tailing Rails Logs

### ISSUE THREAD

**Issue by jaredmoody** [mattbrictson/tomo#214]
Hi, I'm getting to know tomo and enjoying it, thank you so much!

Tailing rails logs is a pretty common task (at least for me?) and typing `tomo run -- puma:log -f` is just long enough to be a little awkward to both remember and type. I can of course alias in my shell or in my app plugin, but what about just creating a little alias method in the puma plugin for this? Something like `tomo puma:tail_log`  sure would be nice I think!

**Comment by mattbrictson** [comment]
Great suggestion! Can you open a PR? 🙏

**Comment by jaredmoody** [comment]
Sure, added this in #215
