### ISSUE TITLE
ProxyJump/Bastion Host

### ISSUE THREAD

**Issue by amree** [mattbrictson/tomo#232]
Hi

Do I need a specific config if I'm using ProxyJump to my host?

I can connect to my server with `ssh myapp` but I failed to run any tomo commands. Based on the `--debug` it failed at:

```
# ...
Authenticated to X.X.X.X ([X.X.X.X]:22).
debug1: channel_connect_stdio_fwd B.B.B.B:22
debug1: channel 0: new [stdio-forward]
debug1: getpeername failed: Bad file descriptor
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
debug1: pledge: network
Connection timed out during banner exchange
debug1: channel 0: free: direct-tcpip: listening port 0 for B.B.B.B port 22, connect from 127.0.0.1 port 65535 to UNKNOWN port 65536, nchannels 1
debug1: fd 0 clearing O_NONBLOCK
Killed by signal 1.
```

```
Host *
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_rsa
  IdentityFile ~/.ssh/id_rsa_bastion

Host bastion
  Hostname X.X.X.X
  User ubuntu

Host myapp
  ProxyJump bastion
  Hostname B.B.B.B
  User ubuntu
```

```ruby
environment :production do
  host "myapp"
  # ...
end
```

Any idea why? Let me know if anyone needs more information

**Comment by mattbrictson** [comment]
Hmm, I don't use `ProxyJump` but I just tried mimicking your SSH config using my own hosts, like this:

```
Host myapp
  ProxyJump bastion
  User deployer
  HostName X.X.X.X

Host bastion
  HostName B.B.B.B
  User deployer
```

I did a `tomo deploy` and it worked fine. With the `--debug` flag I can see the proxy is working:

```
debug1: Setting implicit ProxyCommand from ProxyJump: ssh -v -W '[%h]:%p' bastion
...
Authenticated to X.X.X.X (via proxy).
```

The only clue I see in your logs is this:

```
Connection timed out during banner exchange
```

Is it possible the one of the hosts is waiting for stdin? E.g. prompting for a password? I don't think tomo connects stdin, so this could lead to a hang/timeout if a process is waiting for input.

**Comment by mattbrictson** [comment]
If it helps, my local ssh version is:

```
$ ssh -V
OpenSSH_8.1p1, LibreSSL 2.7.3
```

And my bastion host is using:

```
$ ssh -V
OpenSSH_8.2p1 Ubuntu-4ubuntu0.2, OpenSSL 1.1.1f  31 Mar 2020
```

**Comment by amree** [comment]
Thanks for the reply. I managed to get it working but the thing is I'm not sure what fixed it. I was playing around with the security group but I doubt that was the fix. I'll close this first but I'll post the solution here if I can figure out what fixed it.

Thanks again!
