### ISSUE TITLE
Unable to complete "Deploying Rails From Scratch" tutorial on $4/mo droplet, RAM?

### ISSUE THREAD

**Issue by dhnaranjo** [mattbrictson/tomo#358]
Hi! I was following [Deploying Rails From Scratch](https://cloud.digitalocean.com/droplets/338003411/graphs?i=dd5033&period=hour&preserveScrollPosition=true) with Ruby 3.2.0 and a DO $4/mo droplet, 1vCPU and 512MB RAM, and `tomo setup` / `ruby-build` would bail repeatedly with:

```
  Installing ruby-3.2.0...
  
  BUILD FAILED (Ubuntu 22.10 using ruby-build 20230124-1-g2a2880f)
  
  Inspect or clean up the working tree at /tmp/ruby-build.20230128184600.18970.HFzgKx
  Results logged to /tmp/ruby-build.20230128184600.18970.log
  
  Last 10 log lines:
  compiling enc/unicode.c
  compiling enc/utf_8.c
  compiling enc/trans/newline.c
  compiling ./missing/setproctitle.c
  compiling ./missing/strlcat.c
  compiling ./missing/strlcpy.c
  compiling addr2line.c
  compiling dmyenc.c
  building Rust YJIT (release mode)
  make: *** [yjit/yjit.mk:26: yjit/target/release/libyjit.a] Killed
```

On a hunch I bumped my droplet up to the $6/mo, 1vCPU and 1GB RAM size and everything completed successfully. I recognize that this is not Tomo's fault, but you might want to note that in the tutorial, or something? Iunno.

Anyways, tools rad. Appreciate your effort.

**Comment by mattbrictson** [comment]
Great point! Yes, in my experience you'll need at least 1GB of RAM to build and deploy a basic Rails app these days.

Would you be interested in opening a PR to update the docs and become a contributor to the project? The docs are in Markdown format. A good place for the note about the memory requirement might be this page: `docs/tutorials/deploying-rails-from-scratch.md`
