### ISSUE TITLE
[Question] Is it possible to change the default PUMA port? How do I do that? 

### ISSUE THREAD

**Issue by designium** [mattbrictson/tomo#79]
Hi,

Is there any way to change the PUMA's default port from 3000 to something like '2000'?

I tried changing the config.rb file from TOMO folder but it didn't work so far, the defaults to 3000.

**Comment by mattbrictson** [comment]
You should be able to add:

```ruby
# .tomo/config.rb
set puma_port: 2000
```

And then run this task to regenerate the puma systemd config:

```shell
$ tomo run puma:setup_systemd
```

Let me know if that doesn't work!

**Comment by designium** [comment]
It did work! Thank you.

**Comment by n-at-han-k** [comment]
Do you think adding this to the readme or the documentation would be a good idea?
