### ISSUE TITLE
[Question] Suggestion on how to handle master.key?

### ISSUE THREAD

**Issue by designium** [mattbrictson/tomo#83]
Hi,

I have multiple apps in the same machine. I tried to set the RAILS_MASTER_KEY but then one app will try to use the wrong key.

I thought of the other solution which is to upload the master.key of each app to their directory but is that the right solution?

Cheers,

Chim

**Comment by mattbrictson** [comment]
Hi @designium , good question!

As I mentioned in <https://github.com/mattbrictson/tomo/issues/78#issuecomment-555121565>, tomo's default deployment configuration is not designed to support multiple Rails apps being deployed to a single remote user@host.

My recommendation would be to create multiple users on the host, and then use a different user for deploying each app. That way each user can have its own distinct environment variables and you can easily configure each app differently without risking conflicts.

E.g. app1 would be configured to deploy as:

```ruby
host "app1@example.com"
```

And app2 would be configured to deploy as:

```ruby
host "app2@example.com"
```

I am curious: what is your reasoning for deploying multiple Rails apps to the same host? Is this a cost-saving measure or are there other considerations? Do you have the ability to create other users on the host or are you operating in an environment where that is out of your control?

**Comment by designium** [comment]
@mattbrictson 

The main reason is that I'm doing a lot of prototypes and being able to leverage the same machine leads to cost-saving and also avoid the issue of having to build new machines for every single prototype. 

I think for Production level perspective, having one app in one server is the more appropriate use case. In that case, Tomo does work very well.

For some reason, I have not considered the approach of creating multiple users; one user for one app. I do have control of the server so I could do that. Now, it's unclear to me which approach is better to handle multi-app in single server: create one user per app or the approach I'm proposing. Long story short: creating new user for each app requires keen attention to folders and user ownership and permissions for certain files and directories or setting up certain configurations in TOMO and the Rails apps to achieve similar effect as the first approach.

**Comment by mattbrictson** [comment]
My main concern is that tomo relies on the host user's bash profile for various things, like setting environment variables and initializing rbenv and nodenv. The moment you want to deploy two apps that differ in those requirements (e.g. app1 requires Ruby 2.5 but app2 requires Ruby 2.6), then this no longer works.

So in the long term using separate host users will definitely be safer and give you more flexibility. Creating a user is fairly easy as documented in the [tomo Rails tutorial](https://tomo-deploy.com/tutorials/deploying-rails-from-scratch/):

```
adduser --disabled-password deployer < /dev/null
mkdir -p /home/deployer/.ssh
cp /root/.ssh/authorized_keys /home/deployer/.ssh
chown -R deployer:deployer /home/deployer/.ssh
chmod 600 /home/deployer/.ssh/authorized_keys
mkdir -p /var/www
chown deployer:deployer /var/www
loginctl enable-linger deployer
```

And then you can run `tomo setup` to set everything up for that new user (installing rbenv, etc.). I don't think user permissions will be a problem unless you need to share files between multiple apps for some reason.

**Comment by designium** [comment]
I see. Then I think your method is definitely more robust than the one I'm
suggesting. Also, it will be much easier to explain to other developers
about how to host multiple apps; they create new users and just follow the
default Tomo deployment.

You don't have to accept my pull request based on what we discussed. :)
